// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: protos/generators/generic.proto

package generators

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FormatEnum int32

const (
	FormatEnum_INVALID FormatEnum = 0
	FormatEnum_UNSET   FormatEnum = 1
	FormatEnum_XLSX    FormatEnum = 2
	FormatEnum_PDF     FormatEnum = 3
	FormatEnum_CSV     FormatEnum = 4
	FormatEnum_OTHER   FormatEnum = 5
)

// Enum value maps for FormatEnum.
var (
	FormatEnum_name = map[int32]string{
		0: "INVALID",
		1: "UNSET",
		2: "XLSX",
		3: "PDF",
		4: "CSV",
		5: "OTHER",
	}
	FormatEnum_value = map[string]int32{
		"INVALID": 0,
		"UNSET":   1,
		"XLSX":    2,
		"PDF":     3,
		"CSV":     4,
		"OTHER":   5,
	}
)

func (x FormatEnum) Enum() *FormatEnum {
	p := new(FormatEnum)
	*p = x
	return p
}

func (x FormatEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormatEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_generators_generic_proto_enumTypes[0].Descriptor()
}

func (FormatEnum) Type() protoreflect.EnumType {
	return &file_protos_generators_generic_proto_enumTypes[0]
}

func (x FormatEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormatEnum.Descriptor instead.
func (FormatEnum) EnumDescriptor() ([]byte, []int) {
	return file_protos_generators_generic_proto_rawDescGZIP(), []int{0}
}

// Template information. File to be used as a template by the generator
type Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Template name, used by monitoring
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Subfolder name
	Folder string `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	// Filename
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *Template) Reset() {
	*x = Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_generators_generic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_protos_generators_generic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_protos_generators_generic_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Template) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type Generator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Instance name, used by monitoring
	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// File format to be generated
	Format FormatEnum `protobuf:"varint,2,opt,name=format,proto3,enum=generators.FormatEnum" json:"format,omitempty"`
	// Template used by the generator
	Template *Template `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	// Path and filename to store the generated report temporally
	ReportFilepath string `protobuf:"bytes,4,opt,name=report_filepath,json=reportFilepath,proto3" json:"report_filepath,omitempty"`
	// Data mapper to be used by the generator. The concrete type is defined at mappers.proto file
	DataMapper *any.Any `protobuf:"bytes,5,opt,name=data_mapper,json=dataMapper,proto3" json:"data_mapper,omitempty"`
	// Extra data to be used by the template. Could be fixed values or references to fields using curly braces "{Query.FieldName}"
	TemplateMapper map[string]string `protobuf:"bytes,6,rep,name=template_mapper,json=templateMapper,proto3" json:"template_mapper,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Metadata to be included in the report file
	Metadata *any.Any `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *Generator) Reset() {
	*x = Generator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_generators_generic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Generator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generator) ProtoMessage() {}

func (x *Generator) ProtoReflect() protoreflect.Message {
	mi := &file_protos_generators_generic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generator.ProtoReflect.Descriptor instead.
func (*Generator) Descriptor() ([]byte, []int) {
	return file_protos_generators_generic_proto_rawDescGZIP(), []int{1}
}

func (x *Generator) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Generator) GetFormat() FormatEnum {
	if x != nil {
		return x.Format
	}
	return FormatEnum_INVALID
}

func (x *Generator) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Generator) GetReportFilepath() string {
	if x != nil {
		return x.ReportFilepath
	}
	return ""
}

func (x *Generator) GetDataMapper() *any.Any {
	if x != nil {
		return x.DataMapper
	}
	return nil
}

func (x *Generator) GetTemplateMapper() map[string]string {
	if x != nil {
		return x.TemplateMapper
	}
	return nil
}

func (x *Generator) GetMetadata() *any.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata to be included in the Excel report file
type ExcelMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author  string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Company string `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
}

func (x *ExcelMetadata) Reset() {
	*x = ExcelMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_generators_generic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExcelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelMetadata) ProtoMessage() {}

func (x *ExcelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_protos_generators_generic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelMetadata.ProtoReflect.Descriptor instead.
func (*ExcelMetadata) Descriptor() ([]byte, []int) {
	return file_protos_generators_generic_proto_rawDescGZIP(), []int{2}
}

func (x *ExcelMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExcelMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ExcelMetadata) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

var File_protos_generators_generic_proto protoreflect.FileDescriptor

var file_protos_generators_generic_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xb2, 0x03, 0x0a,
	0x09, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x30, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x08,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x35, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0a, 0x64, 0x61,
	0x74, 0x61, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x0f, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x41,
	0x0a, 0x13, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x57, 0x0a, 0x0d, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2a, 0x4b, 0x0a, 0x0a, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x58, 0x4c, 0x53, 0x58, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x44,
	0x46, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x53, 0x56, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05,
	0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x05, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_generators_generic_proto_rawDescOnce sync.Once
	file_protos_generators_generic_proto_rawDescData = file_protos_generators_generic_proto_rawDesc
)

func file_protos_generators_generic_proto_rawDescGZIP() []byte {
	file_protos_generators_generic_proto_rawDescOnce.Do(func() {
		file_protos_generators_generic_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_generators_generic_proto_rawDescData)
	})
	return file_protos_generators_generic_proto_rawDescData
}

var file_protos_generators_generic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_generators_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_generators_generic_proto_goTypes = []interface{}{
	(FormatEnum)(0),       // 0: generators.FormatEnum
	(*Template)(nil),      // 1: generators.Template
	(*Generator)(nil),     // 2: generators.Generator
	(*ExcelMetadata)(nil), // 3: generators.ExcelMetadata
	nil,                   // 4: generators.Generator.TemplateMapperEntry
	(*any.Any)(nil),       // 5: google.protobuf.Any
}
var file_protos_generators_generic_proto_depIdxs = []int32{
	0, // 0: generators.Generator.format:type_name -> generators.FormatEnum
	1, // 1: generators.Generator.template:type_name -> generators.Template
	5, // 2: generators.Generator.data_mapper:type_name -> google.protobuf.Any
	4, // 3: generators.Generator.template_mapper:type_name -> generators.Generator.TemplateMapperEntry
	5, // 4: generators.Generator.metadata:type_name -> google.protobuf.Any
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_generators_generic_proto_init() }
func file_protos_generators_generic_proto_init() {
	if File_protos_generators_generic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_generators_generic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_generators_generic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Generator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_generators_generic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExcelMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_generators_generic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_generators_generic_proto_goTypes,
		DependencyIndexes: file_protos_generators_generic_proto_depIdxs,
		EnumInfos:         file_protos_generators_generic_proto_enumTypes,
		MessageInfos:      file_protos_generators_generic_proto_msgTypes,
	}.Build()
	File_protos_generators_generic_proto = out.File
	file_protos_generators_generic_proto_rawDesc = nil
	file_protos_generators_generic_proto_goTypes = nil
	file_protos_generators_generic_proto_depIdxs = nil
}
