// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: protos/mappers/mappers.proto

package mappers

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Data type list
type DataTypeEnum int32

const (
	DataTypeEnum_INVALID DataTypeEnum = 0
	DataTypeEnum_UNSET   DataTypeEnum = 1
	DataTypeEnum_STRING  DataTypeEnum = 2
	DataTypeEnum_INTEGER DataTypeEnum = 3
	DataTypeEnum_DECIMAL DataTypeEnum = 4
	DataTypeEnum_BOOLEAN DataTypeEnum = 5
)

// Enum value maps for DataTypeEnum.
var (
	DataTypeEnum_name = map[int32]string{
		0: "INVALID",
		1: "UNSET",
		2: "STRING",
		3: "INTEGER",
		4: "DECIMAL",
		5: "BOOLEAN",
	}
	DataTypeEnum_value = map[string]int32{
		"INVALID": 0,
		"UNSET":   1,
		"STRING":  2,
		"INTEGER": 3,
		"DECIMAL": 4,
		"BOOLEAN": 5,
	}
)

func (x DataTypeEnum) Enum() *DataTypeEnum {
	p := new(DataTypeEnum)
	*p = x
	return p
}

func (x DataTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_mappers_mappers_proto_enumTypes[0].Descriptor()
}

func (DataTypeEnum) Type() protoreflect.EnumType {
	return &file_protos_mappers_mappers_proto_enumTypes[0]
}

func (x DataTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataTypeEnum.Descriptor instead.
func (DataTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_protos_mappers_mappers_proto_rawDescGZIP(), []int{0}
}

// Excel column defition
type ExcelColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Column name (A, B, C, etc)
	ColumnName string `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// Column data type
	ColumnType DataTypeEnum `protobuf:"varint,2,opt,name=column_type,json=columnType,proto3,enum=mappers.DataTypeEnum" json:"column_type,omitempty"`
}

func (x *ExcelColumn) Reset() {
	*x = ExcelColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mappers_mappers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExcelColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelColumn) ProtoMessage() {}

func (x *ExcelColumn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mappers_mappers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelColumn.ProtoReflect.Descriptor instead.
func (*ExcelColumn) Descriptor() ([]byte, []int) {
	return file_protos_mappers_mappers_proto_rawDescGZIP(), []int{0}
}

func (x *ExcelColumn) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *ExcelColumn) GetColumnType() DataTypeEnum {
	if x != nil {
		return x.ColumnType
	}
	return DataTypeEnum_INVALID
}

// Excel data mapper. A map of each query field to the corresponding excel column
type ExcelDataMapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns map[string]*ExcelColumn `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExcelDataMapper) Reset() {
	*x = ExcelDataMapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_mappers_mappers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExcelDataMapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcelDataMapper) ProtoMessage() {}

func (x *ExcelDataMapper) ProtoReflect() protoreflect.Message {
	mi := &file_protos_mappers_mappers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcelDataMapper.ProtoReflect.Descriptor instead.
func (*ExcelDataMapper) Descriptor() ([]byte, []int) {
	return file_protos_mappers_mappers_proto_rawDescGZIP(), []int{1}
}

func (x *ExcelDataMapper) GetColumns() map[string]*ExcelColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_protos_mappers_mappers_proto protoreflect.FileDescriptor

var file_protos_mappers_mappers_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73,
	0x2f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x22, 0x66, 0x0a, 0x0b, 0x45, 0x78, 0x63, 0x65, 0x6c,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x45,
	0x6e, 0x75, 0x6d, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22,
	0xa4, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x45,
	0x78, 0x63, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x1a, 0x50, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e,
	0x45, 0x78, 0x63, 0x65, 0x6c, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x59, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e,
	0x54, 0x45, 0x47, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x43, 0x49, 0x4d,
	0x41, 0x4c, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10,
	0x05, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_mappers_mappers_proto_rawDescOnce sync.Once
	file_protos_mappers_mappers_proto_rawDescData = file_protos_mappers_mappers_proto_rawDesc
)

func file_protos_mappers_mappers_proto_rawDescGZIP() []byte {
	file_protos_mappers_mappers_proto_rawDescOnce.Do(func() {
		file_protos_mappers_mappers_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_mappers_mappers_proto_rawDescData)
	})
	return file_protos_mappers_mappers_proto_rawDescData
}

var file_protos_mappers_mappers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_mappers_mappers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_mappers_mappers_proto_goTypes = []interface{}{
	(DataTypeEnum)(0),       // 0: mappers.DataTypeEnum
	(*ExcelColumn)(nil),     // 1: mappers.ExcelColumn
	(*ExcelDataMapper)(nil), // 2: mappers.ExcelDataMapper
	nil,                     // 3: mappers.ExcelDataMapper.ColumnsEntry
}
var file_protos_mappers_mappers_proto_depIdxs = []int32{
	0, // 0: mappers.ExcelColumn.column_type:type_name -> mappers.DataTypeEnum
	3, // 1: mappers.ExcelDataMapper.columns:type_name -> mappers.ExcelDataMapper.ColumnsEntry
	1, // 2: mappers.ExcelDataMapper.ColumnsEntry.value:type_name -> mappers.ExcelColumn
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_mappers_mappers_proto_init() }
func file_protos_mappers_mappers_proto_init() {
	if File_protos_mappers_mappers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_mappers_mappers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExcelColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_mappers_mappers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExcelDataMapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_mappers_mappers_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_mappers_mappers_proto_goTypes,
		DependencyIndexes: file_protos_mappers_mappers_proto_depIdxs,
		EnumInfos:         file_protos_mappers_mappers_proto_enumTypes,
		MessageInfos:      file_protos_mappers_mappers_proto_msgTypes,
	}.Build()
	File_protos_mappers_mappers_proto = out.File
	file_protos_mappers_mappers_proto_rawDesc = nil
	file_protos_mappers_mappers_proto_goTypes = nil
	file_protos_mappers_mappers_proto_depIdxs = nil
}
