// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: protos/generators/specialized.proto

package generators

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Defines a specialized generator, which is a service with specific logic to generate a report.
// For example a service that gets data from DynamoDB with a very specific data structure
type SpecializedGenerator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Instance name, used for monitoring
	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Name of the generator service that should be executed
	GeneratorName string `protobuf:"bytes,2,opt,name=generator_name,json=generatorName,proto3" json:"generator_name,omitempty"`
	// All information needed by the service in order to generate the report
	Metadata *any.Any `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *SpecializedGenerator) Reset() {
	*x = SpecializedGenerator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_generators_specialized_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecializedGenerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecializedGenerator) ProtoMessage() {}

func (x *SpecializedGenerator) ProtoReflect() protoreflect.Message {
	mi := &file_protos_generators_specialized_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecializedGenerator.ProtoReflect.Descriptor instead.
func (*SpecializedGenerator) Descriptor() ([]byte, []int) {
	return file_protos_generators_specialized_proto_rawDescGZIP(), []int{0}
}

func (x *SpecializedGenerator) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *SpecializedGenerator) GetGeneratorName() string {
	if x != nil {
		return x.GeneratorName
	}
	return ""
}

func (x *SpecializedGenerator) GetMetadata() *any.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata for specialized generator service one (just an example)
type MetadataOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 string `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
}

func (x *MetadataOne) Reset() {
	*x = MetadataOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_generators_specialized_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataOne) ProtoMessage() {}

func (x *MetadataOne) ProtoReflect() protoreflect.Message {
	mi := &file_protos_generators_specialized_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataOne.ProtoReflect.Descriptor instead.
func (*MetadataOne) Descriptor() ([]byte, []int) {
	return file_protos_generators_specialized_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataOne) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

// Metadata for specialized generator service two (just an example)
type MetadataTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 string `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 int32  `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
}

func (x *MetadataTwo) Reset() {
	*x = MetadataTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_generators_specialized_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataTwo) ProtoMessage() {}

func (x *MetadataTwo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_generators_specialized_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataTwo.ProtoReflect.Descriptor instead.
func (*MetadataTwo) Descriptor() ([]byte, []int) {
	return file_protos_generators_specialized_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataTwo) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

func (x *MetadataTwo) GetField2() int32 {
	if x != nil {
		return x.Field2
	}
	return 0
}

var File_protos_generators_specialized_proto protoreflect.FileDescriptor

var file_protos_generators_specialized_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a,
	0x14, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x0b, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x31, 0x22, 0x3d, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x54, 0x77, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32,
	0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_generators_specialized_proto_rawDescOnce sync.Once
	file_protos_generators_specialized_proto_rawDescData = file_protos_generators_specialized_proto_rawDesc
)

func file_protos_generators_specialized_proto_rawDescGZIP() []byte {
	file_protos_generators_specialized_proto_rawDescOnce.Do(func() {
		file_protos_generators_specialized_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_generators_specialized_proto_rawDescData)
	})
	return file_protos_generators_specialized_proto_rawDescData
}

var file_protos_generators_specialized_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_generators_specialized_proto_goTypes = []interface{}{
	(*SpecializedGenerator)(nil), // 0: generators.SpecializedGenerator
	(*MetadataOne)(nil),          // 1: generators.MetadataOne
	(*MetadataTwo)(nil),          // 2: generators.MetadataTwo
	(*any.Any)(nil),              // 3: google.protobuf.Any
}
var file_protos_generators_specialized_proto_depIdxs = []int32{
	3, // 0: generators.SpecializedGenerator.metadata:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_generators_specialized_proto_init() }
func file_protos_generators_specialized_proto_init() {
	if File_protos_generators_specialized_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_generators_specialized_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecializedGenerator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_generators_specialized_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_generators_specialized_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_generators_specialized_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_generators_specialized_proto_goTypes,
		DependencyIndexes: file_protos_generators_specialized_proto_depIdxs,
		MessageInfos:      file_protos_generators_specialized_proto_msgTypes,
	}.Build()
	File_protos_generators_specialized_proto = out.File
	file_protos_generators_specialized_proto_rawDesc = nil
	file_protos_generators_specialized_proto_goTypes = nil
	file_protos_generators_specialized_proto_depIdxs = nil
}
